
schema_version = "1.0.0"


id = "majik_blender_edu_teacher"


version = "1.1.4"
name = "Majik Blender Edu"
tagline = "Submission integrity tool for educators to verify students' work"
maintainer = "Zelijah"

type = "add-on"


blender_version_min = "4.2.0"


license = [
    "SPDX:GPL-3.0-or-later"
]

copyright = [
    "2026 Zelijah"
]


website = "https://thezelijah.world/tools/education-majik-blender-edu"
documentation = "https://github.com/jedlsf/majik-blender-edu"


tags = ["Pipeline"]


platforms = ["windows-x64", "macos-arm64", "macos-x64", "linux-x64"]



wheels = [
    # ==========================================
    # CRYPTOGRAPHY - cp311-abi3
    # ==========================================
    
    # cp311-abi3 (Python 3.11+)
    "./wheels/cryptography-46.0.3-cp311-abi3-win_amd64.whl",
    "./wheels/cryptography-46.0.3-cp311-abi3-macosx_10_9_universal2.whl",
    "./wheels/cryptography-46.0.3-cp311-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
    
 
    # ==========================================
    # CFFI - Python 3.11 (Blender 4.1-5.0+)
    # ==========================================
    
    "./wheels/cffi-2.0.0-cp311-cp311-win_amd64.whl",
    "./wheels/cffi-2.0.0-cp311-cp311-macosx_10_13_x86_64.whl",
    "./wheels/cffi-2.0.0-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/cffi-2.0.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
]



[permissions]
network = "Access required for JSON file analysis"
files = "Read/write keys and logs as JSON for integrity verification"
